nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': 
            allow_origin: ['http://127.0.0.1:8000/api/']
            allow_headers: ['content-type', 'authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
            max_age: 3600
